### PR TITLE
Sync ACIS tables

### PR DESCRIPTION
**Pull request by jzuhone**
## Description

Add the `acis_tables` directory, which appropriately enough contains the ACIS tables, to `ska_sync`.

## Interface impacts

Adds two new files totaling about 2.5 Mb to the standard Ska data in `$SKA/data/acis_tables`.

### Unit tests

- [x] No unit tests

### Functional tests

- [x] @taldcroft installed the new sync config and confirmed that the ACIS tables get synced
- [x] @jzuhone installed the new sync config and confirmed that the ACIS tables get synced, verified that they can be read in the same way as before

### CODE REVIEW

**Comment by jzuhone** [comment]
@taldcroft I forgot to tag you here

**Review by taldcroft — APPROVED** [review]
@jzuhone thanks, LGTM. You should just do the testing and we can merge this.

**Comment by jzuhone** [comment]
@taldcroft Did you set up the cron  job to copy in the ACIS tables to `/proj/sot/ska/data/acis_tables`?

**Comment by taldcroft** [comment]
@jzuhone - yes, there is now a daily job on HEAD (kady) to do this:
```
rsync -aL /data/acis/sacgs/odb/current* /proj/sot/ska/data/acis_tables/
```

**Comment by jzuhone** [comment]
@taldcroft I was also able to sync the files, and I tested that they could be read correctly.

**Pull request merged**
